server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    max-http-form-post-size: 5MB


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql:///peop_db
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: Create123!@#
  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 5MB
  banner:
    location: classpath:banner.txt


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: com.example.pojo

  #jwt配置
jwt:
  token:
    tokenExpiration: 1440 #有效时间,单位分钟
    tokenSignKey: prop123456  #当前程序签名秘钥 自定义

